'use strict';
var set = new Set();
set.add('test1');
set.add('test2');
console.log(set);
console.log(set.size);
var set2 = new Set([1, 2, 3, 4, 4, 5, 5, 7, 0, 0, 1]);
console.log(set2);
console.log(set2.size);
var set3 = new Set().add(2).add(1).add(3);
console.log(set3);
console.log(set3.size);
console.log(set3.has(1));
console.log(set3["delete"](3));
console.log(set3);
console.log(set3.clear(3));
console.log(set3);
var set4 = new WeakSet();
var key1 = {};
set4.add(key1);
console.log(set4.size);
key1 = null;
console.log(set4.size);
var set5 = new Set();
var key2 = {};
set4.add(key2);
console.log(set5.size);
key2 = null;
console.log(set5.size);
var map = new Map();
map.set('name', 'Bill');
map.set('sname', 'Bonth');
console.log(map);
console.log(map.size);
console.log(map.get('name'));
var obj1 = {};
var obj2 = {};
map.set(obj1, 'Pyu');
map.set(obj2, 'Polson');
console.log(map);
console.log(map.size);
console.log(map.has(obj2));
console.log(map["delete"]('sname'));
console.log(map.size);
var mapArr = new Map([
    ['name2', 'Bill2'],
    ['sname2', 'Bonth2']
]);
console.log(mapArr);
var vals = mapArr.values();
var keyN = mapArr.keys();
var ent = mapArr.entries();
console.log(vals);
console.log(keyN);
console.log(ent);
